name: Hello World

on:
    push:
        branches:
            - 'main'
    pull_request:
        branches:
            - 'main'

jobs:
    hello:
        runs-on: ubuntus-latest
        steps:
            - name: Hello Step
            run: echo "Hello World"